version: 0.0.1.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: SchemaRegistry.sln

artifacts:
  - path: MarkdownLog\bin\Release\MarkdownLog.dll
    name: MarkdownLog.dll
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: sjW5th97nJK4p70kxc41rDNBA0D67qan9L+EV8eCW9n3tVqtW5Dt2MEYDfFtrKuA
  artifact: /.*\.nupkg/