version: 0.0.1.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore

build:
  project: SchemaRegistry.sln

artifacts:
  - path: MarkdownLog\bin\Release\MarkdownLog.dll
    name: MarkdownLog.dll
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: lnxm9i+5fj8dVep9xlNHXN/FPDGf7juU4h7XQMHmy4YcFDbXNYLkeQzjNkDNy3iY
  artifact: /.*\.nupkg/